---
- name: create interface directory
  ansible.builtin.file:
    path: "/etc/firewall.lihas.d/interface-{{ iface }}"
    state: directory
    mode: '0750'
  tags:
    - firewall_config
- name: debug group/iface
  ansible.builtin.debug:
    msg: "group {{ configgroup }}, iface {{ iface }}"
- name: "firewall for interface {{ iface }}"
  ansible.builtin.template:
    dest: "/etc/firewall.lihas.d/interface-{{ iface }}/{{ file }}"
    src: "etc/firewall.lihas.d/interface/common.j2"
    mode: '0640'
  loop:
    - comment
    - network
    - privclients
    - snat
    - dnat
    - masquerade
    - mark
  loop_control:
    loop_var: file
  notify: reload_firewall-lihas
  tags:
    - firewall_config
