---
- name: Link common interface directories
  ansible.builtin.file:
    src: "/etc/firewall.lihas.d/interface-{{ iface }}"
    path: "/etc/firewall.lihas.d/interface-{{ file }}"
    state: link
    force: true
  loop: "{{ hostvars[inventory_hostname][configgroup]['config']['firewall']['interface_links'][iface] | default([]) }}"
  loop_control:
    loop_var: file
  notify: Reload firewall-lihas
  tags:
    - firewall_config
